version: '2'

services:
  basercake3-database:
    container_name: basercake3-database
    image: mysql/mysql-server:5.7
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "basercms"
  basercake3:
    container_name: basercake3
    image: baserproject/basercms
    volumes:
#      - sync-volume:/var/www/html
      - .:/var/www/html:cached
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
#    command:
#      composer install
    ports:
      - "80:80"
    depends_on:
      - basercake3-database
volumes:
  sync-volume:
    external: true